### ISSUE TITLE
Actualización Carta Porte no reflejada

### ISSUE THREAD

**Issue by gam04** [phpcfdi/resources-sat-xml#1]
Hola a todos, de ante mano muchas gracias por este recurso.

Solo quería informar que la actualización para el complemento Carta Porte no se ve reflejada en los recursos de este proyecto.

El SAT libero la version 2.0 del complemento y los recursos relacionados son los siguientes:

XSD: http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte20.xsd
XSLT: http://omawww.sat.gob.mx/tramitesyservicios/Paginas/documentos/CartaPorte20.xslt
Catalogo XSD: http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte/catCartaPorte.xsd

Saludos.

**Comment by eclipxe13** [comment]
Saludos.

Como dice en [Actualización del recurso](https://github.com/phpcfdi/resources-sat-xml#actualizaci%C3%B3n-del-recurso), depende de [phpcfdi/resources-sat-xml-generator](https://github.com/phpcfdi/resources-sat-xml-generator) que a su vez depende de [phpcfdi/sat-ns-registry](https://github.com/phpcfdi/sat-ns-registry)

Existe el issue https://github.com/phpcfdi/sat-ns-registry/issues/3 *Registrar el Complemento Carta Porte versión 2.0* que trata este tema. Una vez incluido en ese repositorio se hará la descarga automática en este recurso.

Si gustas puedes participar de la discusión en el issue https://github.com/phpcfdi/sat-ns-registry/issues/3

**Comment by gam04** [comment]
Hola @eclipxe13 , justo vengo de ese issue , por eso  marque este como resuelto.
Ando intercambiando mensajes con el SAT para ver si pueden aplicar el cambio.

Muchas gracias.
